#NAMD3 minimization uses CPU code this setting is required for cpu
CUDASOAintegrate    off

# Forcefield/Topology Information
paraTypeCharmm      off
amber               yes
coordinates         ../../models/LIG/complex.pdb
parmfile            ../../models/LIG/complex.top
readexclusions      no

# Unchanging information
################################################################################
# Force-Field Parameters
exclude             scaled1-4
1-4scaling          0.833333
cutoff              12.
switching           on
switchdist          10.
pairlistdist        13.5
# Integrator Parameters
timestep            2.0  ;# 2fs/step
rigidBonds          all  ;# needed for 2fs steps
rigidtolerance      0.00001
rigidIterations     100
nonbondedFreq       1
fullElectFrequency  2
stepspercycle       10
wrapWater           on
wrapAll             on
# Output
outputEnergies      10000
outputPressure      10000

# Protocol specific information
################################################################################

# Langevin temperature
langevin            on    ;# do langevin dynamics
langevinDamping     5     ;# damping coefficient (gamma) of 5/ps
langevinTemp        300
langevinHydrogen    no    ;# dont couple langevin bath to hydrogens

temperature 50

# Output and restart
set output_root "eq0"
stdout [format $output_root.log]
outputname [format $output_root]
restartname [format $output_root]
XSTfile [format $output_root.xst]

binaryoutput        yes
binaryrestart       yes
restartfreq         1000
xstFreq             1000
dcdfreq             200
dcdfile             min.dcd
#DCDUnitcell  yes

########Turn on/off implicit solvent during minimization#######
if {0} {
# GBIS: Generalized born implicit solvent
GBIS on 
ionConcentration 0.30
SASA off
}

########Run minimization#######
set ts 0

## dcd file with poses stored earlier in initial_search
coorfile open dcd ../../output_combined_trajectories/dcds/rec_4ui5.LIG.dcd

while { ![coorfile read] } {
    firstTimestep $ts 
    # minimization time	
    minimize 200 
}
coorfile close
