#NAMD3
CUDASOAintegrate    on

# Forcefield/Topology Information
paraTypeCharmm      off
amber               yes
parmfile            ../../../build/complex.top
readexclusions      no
coordinates         ../../../build/complex.pdb

# Unchanging information
################################################################################
# Force-Field Parameters
exclude             scaled1-4
1-4scaling          0.833333
cutoff              12.
switching           on
switchdist          10.
pairlistdist        13.5
# Integrator Parameters
timestep            2.0  ;# 2fs/step
rigidBonds          all  ;# needed for 2fs steps
rigidtolerance      0.00001
rigidIterations     100
nonbondedFreq       1
fullElectFrequency  2
stepspercycle       10
wrapWater           on
wrapAll             on
# Output
outputEnergies      10000
outputPressure      10000

# Protocol specific information
################################################################################

PME                 yes
PMEGridSpacing      1.0

# Langevin temperature
langevin            on    ;# do langevin dynamics
langevinDamping     5     ;# damping coefficient (gamma) of 5/ps
langevinTemp        300
langevinHydrogen    no    ;# dont couple langevin bath to hydrogens

# pressure - NAMD3 cant use Berendsen
useGroupPressure      yes ;# needed for 2fs steps
useFlexibleCell       no  ;# no for water box, yes for membrane
useConstantArea       no  ;# no for water box, yes for membrane
langevinPiston        on               # Nose-Hoover Langevin piston pressure control
langevinPistonTarget  1.01325          # target pressure in bar 1atm = 1.01325bar
langevinPistonPeriod  50.0             # oscillation period in fs. correspond to pgamma T=50fs=0.05ps
langevinPistonTemp    300              # f=1/T=20.0(pgamma)
langevinPistonDecay   25.0             # oscillation decay time. smaller value correspons to larger random
                                       # forces and increased coupling to the Langevin temp bath.
                                       # Equall or smaller than piston period
                
# Output and restart
set restart_root "eq0" ; # directory must exist
set output_root "eq1" ; # directory must exist

binaryoutput        yes
binaryrestart       yes
restartfreq         500000
xstFreq             5000
dcdfreq             10000
DCDUnitcell         yes
stdout [format $output_root.log]
outputname [format $output_root]
restartname [format $output_root]
XSTfile [format $output_root.xst]

# Coordinates, velocities and cell size
bincoordinates [format $restart_root.coor]
binvelocities [format $restart_root.vel]
extendedSystem [format $restart_root.xsc]

run 500000
